name: food_nutrition_analyzer
description: AI-powered Food Nutrition Analyzer for Diabetes Patients
publish_to: 'none'
version: 1.0.0+1


environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.2.0
  # Image Picking
  image_picker: ^1.0.4

  # HTTP Requests (Nutrition API)
  http: ^1.1.0

  # Firebase
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6

  # Google ML Kit - Food Detection
  google_mlkit_image_labeling: ^0.9.0

  # Voice Features
  speech_to_text: ^6.6.0
  flutter_tts: ^3.8.5

  # UI & Utilities
  cupertino_icons: ^1.0.2
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0
  fl_chart: ^0.65.0
  lottie: ^2.7.0
  shared_preferences: ^2.2.2
  intl: ^0.18.1
  provider: ^6.1.1
  uuid: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
